Repository repasscloud/software-library, pull requests merged in 2020-07, with the labels that each got.

#14 testing automerge label
  .github/auto-merge.yml
Labels: automerge

#16 [autoupdate] :: app/VideoLAN.VLC/3.0.11
  app/VideoLAN/VLC/3.0.11.json
  app/VideoLAN/VLC/latest.json
Labels: automerge

#20 Testing nuspec file read-in value
  app/7zip/7Zip/latest.json
Labels: automerge

#22 app/video lan.vlc/3.0.11
  app/7zip/7Zip/19.0.json
  app/7zip/7Zip/latest.json
  app/AgileBits/1Password/7.3.705.json
  app/AgileBits/1Password/latest.json
  app/GitProject/git-scm/2.27.0.json
  app/GitProject/git-scm/latest.json
  app/Microsoft/DotNet 4/4.6.2.json
  app/Microsoft/DotNet 4/latest.json
  app/Mozilla/Firefox/78.0.2.json
  app/Mozilla/Firefox/latest.json
  app/Spotify/Spotify/1.1.36.734.json
  app/Spotify/Spotify/latest.json
  app/VideoLAN/VLC/3.0.11.json
  app/VideoLAN/VLC/latest.json
  app/google/Chrome/83.0.4103.116.json
  app/google/Chrome/latest.json
  app/npp/NotePad-Plus-Plus/7.8.7.json
  app/npp/NotePad-Plus-Plus/7.8.8.json
  app/npp/NotePad-Plus-Plus/latest.json
  lib/legacy/main_x86_64_vlc.ps1
Labels: automerge

#26 [autoupdate] :: app/VideoLAN.VLC/3.0.11
  app/VideoLAN/VLC/3.0.11.json
  app/VideoLAN/VLC/latest.json
Labels: automerge

#27 [autoupdate] :: app/VideoLAN.VLC/3.0.11
  app/VideoLAN/VLC/3.0.11.json
  app/VideoLAN/VLC/latest.json
Labels: application request 🈸, automerge

#29 Add a Codacy badge to README.md
  README.md
Labels: automerge

#30 Patch/28
  lib/scripts/Set-InstallerLanguages.ps1
Labels: automerge, bug, patch/_fix

#31 🚧 Revert "Patch/28"
  lib/scripts/Set-InstallerLanguages.ps1
Labels: automerge

#40 fixes Codacy error #37
  lib/scripts/Export-InstallerLanguages.ps1
  lib/scripts/Export-NuspecValue.ps1
  lib/scripts/Get-ApplicationCategory.ps1
  lib/scripts/Get-ApplicationParticulars.ps1
  lib/scripts/Get-JsonCopyrightNotice.ps1
  lib/scripts/Show-HostOutput.ps1
Labels: automerge, codacy, patch/_fix

#49 [autoupdate] :: app/Mozilla.Firefox/78.0.2
  app/Mozilla/Firefox/78.0.2.json
  app/Mozilla/Firefox/latest.json
Labels: application request 🈸

#50 Add .circleci/config.yml
  .circleci/config.yml
Labels: automerge

#51 ci/circleci tests
  .circleci/config.yml
Labels: DO-NOT-MERGE, WIP, locked-issue

#68 ci/auto builder macdev
  appveyor.yml
Labels: automerge
